### ISSUE TITLE
How does this compare to https://github.com/gravicappa/shen-js

### ISSUE THREAD

**Issue by Gozala** [rkoeninger/ShenScript#1]
Hi

I'm just curious how does this compares to https://github.com/gravicappa/shen-js or how complete current implementation is.

Thanks

**Comment by rkoeninger** [comment]
@Gozala Close if you feel your curiosity has been satisfied.

**Comment by rkoeninger** [comment]
@Gozala Trampolines only help when it's a tail call, so maybe there's a long chain of non-tail calls in whichever test was failing. My memory is spotty at this point.

I'm not familiar with web workers, but if you have an idea how they could be used to do sync IO, I'll try to implement it.

If you want to try it out, you can build it using the instructions in the readme. There's a translate button on the index.html page that will output javascript. [Here's the section of the transpiler that does interop.](https://github.com/rkoeninger/ShenScript/blob/master/src/transpiler.js#L355-L367) Putting the `js.` prefix on a function outputs that function as-is without translating its name and writting a form like `(js. "jscode")` outputs `jscode` as a literal in-line in the output javascript string.

shen-js has an online hosted interactive prompt with working repl [here](http://gravicappa.github.io/shen-js/shen.html#.doc/welcome.html).

**Comment by Gozala** [comment]
> @Gozala Trampolines only help when it's a tail call, so maybe there's a long chain of non-tail calls in whichever test was failing. My memory is spotty at this point.

But that is also the case with [JS tail call optimization](https://github.com/lukehoban/es6features#tail-calls).

> I'm not familiar with web workers, but if you have an idea how they could be used to do sync IO, I'll try to implement it.

I guess it depends on what IO you have in mind. I was assuming you needed sync IO to read files which in browsers would probably mean loading it from server. That could be done with [sync XHR](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open#Parameters) in the web worker without blocking the UI thread.

If you meant reading from STDIN that is probably still doable by also adding [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) into the mix. Idea would be that worker would request sync XHR that will end up creating [FetchEvent](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith) in service worker that can respond with a promise, which will resolve with request body of the other request comping from the UI thread.

One major limitation is you won't have access to DOM in the web workers, but I presume most shen programs that exist do not either so for REPL it might be fine.

> If you want to try it out, you can build it using the instructions in the readme. There's a translate button on the index.html page that will output javascript. Here's the section of the transpiler that does interop. Putting the js. prefix on a function outputs that function as-is without translating its name and writting a form like (js. "jscode") outputs jscode as a literal in-line in the output javascript string.

Thanks, I'll give it a try.

> shen-js has an online hosted interactive prompt with working repl here.

Yeah I was able to use hosted repl but was unable to compile anything on my machine due to https://github.com/gravicappa/shen-js/issues/13 which just got fixed :)
