### ISSUE TITLE
Vulnerabilities upon npm install

### ISSUE THREAD

**Issue by emummel20** [rkoeninger/ShenScript#34]
Hi - fyi getting the following upon running npm install

```
MacBook-Pro ShenScript-master % npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

added 701 packages, and audited 702 packages in 14s

26 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (5 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

Is this normal? Anything I need to do to fix these?

**Comment by rkoeninger** [comment]
Hi @emummel20 , I haven't been actively maintaining this project recently but the vulnerabilities have accumulated.

Let me get node installed on this machine and I'll get vuln fixes pushed.

**Comment by rkoeninger** [comment]
OK, I think it's fixed with https://github.com/rkoeninger/ShenScript/commit/13986fbdf1abd4b299b646c5f3b84e5fcc373b13

`git pull` and try again, reopen this issue if there's still a probem.

**Comment by emummel20** [comment]
Awesome - appreciate it!!
